[env]
RUST_LOG = "debug"
PORT = 8080

[tasks.run-fetcher]
description = "Run fetcher"
workspace = false
script = "cargo run -p fetcher -- ${@}"

[tasks.run-api-server]
description = "Run api server"
workspace = false
script = "cargo run -p api_server"

[tasks.openapi_client]
description = "Generate openapi_client from rate-stocker.yaml"
workspace = false
script = '''
openapi-generator-cli generate \
-i rate-stocker.yaml \
-g rust-server \
-o ./openapi_client
cargo fmt -p openapi_client
'''
